# Generated by Django 4.2.1 on 2023-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0002_remove_product_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Ürünün Açıklaması'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ürün Fiyatı'),
        ),
    ]
