# Generated by Django 4.2.1 on 2023-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0003_product_product_detail_product_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_detail',
            new_name='product_detail',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_price',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Ürünün fotoğrafı'),
        ),
    ]
