# Generated by Django 4.2.1 on 2023-06-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
