# Generated by Django 4.2.1 on 2023-06-11 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appKozmetik', '0013_remove_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Saat'),
        ),
    ]
